# Use an existing base image
FROM ubuntu:20.04

# Set the working directory in the container
WORKDIR /app

# Copy files from the host machine to the container
COPY . .

# Run a command to install dependencies or execute any setup tasks
RUN apt-get update && \
    apt-get install -y <package-name>

# Specify the command to run when the container starts
CMD ["./app"]
